apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gena
  namespace: <YOUR_NAMESPACE>
spec:
  selector:
    matchLabels:
      app: go-gena
  template:
    metadata:
      labels:
        app: go-gena
    spec:
      containers:
      - name: go-gena
        image: ghcr.io/mmogylenko/go-gena:latest
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080